import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const source = readFileSync(join(process.cwd(), 'src/plugin.js'), 'utf8')

assert.match(source, /const ID = 'hermes-tackmark'/, 'plugin id matches install folder')
assert.match(source, /id: 'floating-browser'/, 'uses a fresh floating pane identity')
assert.match(source, /placement: 'floating'/, 'uses native floating pane placement')
assert.match(source, /id: 'floating-browser'[\s\S]*anchor: 'top-left'/, 'opens browser in Orca-style top-left position')
assert.match(source, /KEYBINDS_AREA/, 'registers a rebindable shortcut')
assert.match(source, /mod\+alt\+a/, 'ships the Orca-style show-hide shortcut')
assert.match(source, /PALETTE_AREA/, 'registers a command-palette action')
assert.match(source, /setZoomFactor/, 'controls Chromium page zoom')
assert.match(source, /tackmark-zoom/, 'handles Ctrl or Cmd plus wheel zoom from the guest')
assert.match(source, /beginFloatingResize/, 'provides a draggable resize grip')
assert.match(source, /minimizeFloatingBrowser/, 'provides minimize behavior')
assert.match(source, /toggleMaximizeFloatingBrowser/, 'provides maximize and restore behavior')
assert.match(source, /hideFloatingBrowser/, 'provides session-preserving hide behavior')
assert.match(source, /toggleFloatingBrowser/, 'provides a persistent launcher toggle')
assert.match(source, /beginLauncherDrag/, 'launcher can be moved freely')
assert.match(source, /if \(!launcherDragged\)/, 'launcher click is resolved on pointerup')
assert.doesNotMatch(source, /onClick: \(\) => \{[\s\S]{0,120}launcherDragged/, 'launcher no longer relies on swallowed click')
assert.match(source, /TackMark — compact/, 'minimize renders a distinct compact browser bar')
assert.match(source, /WINDOW_STATE_EVENT/, 'minimize and restore synchronize UI state')
assert.match(source, /card\.style\.width = '360px'/, 'minimize uses a compact browser width')
assert.match(source, /card\.style\.height = '220px'/, 'minimize keeps a usable live browser preview')
assert.match(source, /compact preview/, 'compact state visibly remains a browser window')
assert.match(source, /card\.style\.zIndex = '60'/, 'launcher stays above the browser')
assert.match(source, /launcherPosition/, 'launcher position is persisted')
assert.match(source, /id: 'floating-launcher'/, 'registers an independent top-right launcher')
assert.match(source, /minimizedRestoreSize/, 'minimizes without unmounting and remembers both dimensions')
assert.match(source, /restoreLegacyNativeCollapse/, 'recovers a stale native-collapsed pane before showing')
assert.match(source, /clearLegacyCollapsedState\(\)/, 'clears persisted legacy collapse before pane registration')
assert.match(source, /if \(!card \|\| floatingBrowserExpanded\(card\)\) return false/, 'native recovery runs only for legacy collapsed state')
const minimizeBody = source.slice(source.indexOf('function minimizeFloatingBrowser()'), source.indexOf('function toggleMaximizeFloatingBrowser()'))
assert.doesNotMatch(minimizeBody, /nativeCollapseButton/, 'custom minimize never unmounts the webview')
assert.match(source, /zoomPercent/, 'persists and displays page zoom')
assert.match(source, /import \{ draftInComposer \}/, 'uses the tested editable composer bridge')
assert.match(source, /draftInComposer\(text, images\)/, 'stages the complete batch in the composer')
assert.match(source, /pending\.map\(annotation => annotation\.screenshot\)/, 'passes captured screenshots to the composer bridge')
assert.match(source, /capturePage/, 'captures element screenshot evidence')
assert.match(source, /Draft in chat/, 'labels the non-sending draft action clearly')
assert.doesNotMatch(source, /host\.request\('prompt\.submit'/, 'never submits directly to the agent')
assert.match(source, /document\.createElement\('webview'\)/, 'uses Electron native webview')
assert.match(source, /executeJavaScript\(ANNOTATION_SCRIPT\)/, 'injects annotation script into guest')
assert.match(source, /persist:hermes-preview/, 'shares the stable Hermes preview partition')
assert.match(source, /setAttribute\('src', loadedUrl \|\| 'about:blank'\)/, 'sets initial URL before webview attachment')
assert.match(source, /window\.__tackmarkQueue/, 'guest-to-host annotation queue exists')
assert.match(source, /jsx\(Input,/, 'uses native Hermes Input')
assert.match(source, /jsx[s]?\(Button,/, 'uses native Hermes Button')
assert.match(source, /h-9 shrink-0 items-center/, 'uses compact browser navigation row')
assert.match(source, /h-8 shrink-0 items-center/, 'uses slim TackMark action row')
assert.match(source, /name: 'arrow-left'/, 'provides browser back navigation')
assert.match(source, /name: 'arrow-right'/, 'provides browser forward navigation')
assert.match(source, /absolute top-3 right-3 left-3/, 'renders errors inside the viewport')
assert.doesNotMatch(source, /fetch\(targetUrl/, 'does not CORS-fetch target pages')
assert.doesNotMatch(source, /iframe\.srcdoc/, 'does not reconstruct pages with srcdoc')
assert.doesNotMatch(source, /function fitPreview/, 'does not scale or compress the target page')
assert.doesNotMatch(source, /Page loaded without annotation/, 'does not silently fall back without annotation')

console.log('53 passed, 0 failed — native webview architecture')
